In [1]:
import csv
import pandas as pd
import numpy as np
result = pd.read_csv('Results/finalchangeschool&hospital.csv')
#display(result)

,Unnamed: 0,Suburb,Rent,Distance,SchoolNo,CrimeNo,Buy_Price,HospitalNo,SupermarketNo,StationNo,...,NormSupermarket,NormStation,Rent2bedroomflat,Rent3bedroomflat,Rent2bedroomhouse,Rent3bedroomhouse,Rent4bedroomhouse,RentAverageAll,School_Number,Hospital_Number
0,0,Abbotsford,630,3.2,3,1154,1290000,0,6,8,...,30,40,540,800,600,750,0,475,1,0
1,1,Albert Park,795,3.0,1,605,2150000,0,3,8,...,15,40,500,790,675,950,1100,570,2,0
2,2,Alfredton,360,104.9,2,310,410000,4,2,19,...,10,95,240,310,260,310,380,309,1,0
3,3,Alphington,590,7.0,3,219,1778500,1,7,3,...,35,15,445,590,500,650,800,410,1,1
4,4,Altona,423,13.2,3,595,950000,1,15,20,...,75,100,350,410,360,385,420,400,2,1
5,5,Armadale,835,6.7,2,480,2107500,0,20,1,...,100,5,500,710,645,900,1330,495,1,0
6,6,Ascot Vale,510,5.5,3,1046,1192500,1,20,20,...,100,100,400,525,500,580,730,440,3,0
7,7,Ashburton,530,11.6,3,354,1815000,1,7,2,...,35,10,450,550,425,500,630,460,2,1
8,8,Aspendale,455,26.6,2,253,1122500,1,1,20,...,5,100,380,475,400,460,550,430,2,1
9,9,Avondale Heights,420,10.0,2,313,850000,0,1,20,...,5,100,400,450,400,430,575,420,1,0
10,10,Balwyn,700,10.4,5,417,2360000,0,8,20,...,40,100,428,600,430,550,795,520,2,0
11,11,Barwon Heads,450,66.4,1,120,930500,0,1,20,...,5,100,340,395,350,400,470,400,1,0
12,12,Bayswater,400,26.9,7,910,805500,1,0,0,...,0,0,350,400,345,400,445,380,4,1
13,13,Beaumaris,798,20.1,2,261,1600000,0,5,20,...,25,100,470,685,525,728,995,570,3,0
14,14,Belmont,370,67.7,10,809,495000,1,0,0,...,0,0,310,378,330,375,430,365,7,1
15,15,Bentleigh,580,13.2,4,630,1450000,2,14,20,...,70,100,443,585,450,550,750,490,2,2
16,16,Berwick,410,41.2,10,1905,672500,7,10,10,...,50,50,335,380,340,380,420,400,9,7
17,17,Blackburn,450,16.8,4,469,1410000,1,19,4,...,95,20,400,475,390,450,570,430,4,1
18,18,Boronia,390,29.0,4,1645,731500,1,10,20,...,50,100,360,410,345,400,465,385,4,1
19,19,Box Hill,390,13.7,3,1211,1760000,3,9,20,...,45,100,450,515,400,470,600,435,1,0
20,20,Brighton,975,11.3,8,930,2830000,4,20,20,...,100,100,540,750,620,920,1295,650,3,4
21,21,Broadmeadows,340,15.3,2,2950,545000,1,8,0,...,40,0,340,360,340,360,430,369,6,1
22,22,Brunswick,580,5.3,2,2541,1204000,1,18,0,...,90,0,450,663,530,680,825,460,2,1
23,23,Bulleen,473,12.5,4,356,1300000,0,2,20,...,10,100,440,535,395,480,583,480,1,0
24,24,Bundoora,410,15.8,7,1962,752500,5,9,13,...,45,65,360,430,360,400,430,390,4,5
25,25,Buninyong,370,96.7,2,134,467500,0,0,6,...,0,30,245,300,265,325,390,330,1,0
26,26,Burwood,470,12.3,4,701,1370000,0,16,20,...,80,100,450,550,425,500,630,460,1,0
27,27,Camberwell,750,8.4,3,836,2295000,1,8,20,...,40,100,450,630,533,646,870,490,2,1
28,28,Canterbury,850,10.5,5,175,3051000,2,18,2,...,90,10,430,600,468,650,920,500,3,2
29,29,Carlton,675,2.0,2,1625,1477500,2,1,0,...,5,0,520,670,550,775,960,420,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122,122,Rowville,460,26.5,6,1298,865000,0,6,5,...,30,25,375,420,0,430,500,450,5,0
123,123,Roxburgh Park,410,19.9,2,952,515000,1,5,11,...,25,55,340,360,340,360,430,369,4,0
124,124,Scoresby,400,24.1,3,445,881500,0,4,20,...,20,100,375,415,388,420,500,440,2,0
125,125,Seaford,390,35.2,9,1575,700000,0,6,20,...,30,100,330,370,330,367,450,370,7,0
126,126,Sebastopol,290,101.7,3,924,257000,0,5,20,...,25,100,240,285,250,280,360,280,2,0
127,127,Seymour,300,89.1,1,936,277000,1,5,4,...,25,20,218,0,260,280,363,270,1,1
128,128,South Melbourne,650,0.1,3,1906,1532500,0,8,14,...,40,70,550,720,600,790,0,525,1,0
129,129,Spotswood,471,7.1,1,225,1040000,0,0,20,...,0,100,360,545,450,515,675,470,1,0
130,130,Springvale,380,22.5,4,1957,780000,2,16,20,...,80,100,350,420,350,390,480,380,4,2
131,131,St Albans,350,16.3,13,3176,622000,4,20,20,...,100,100,320,350,320,350,400,350,11,0
132,132,St Kilda,620,6.1,4,3436,1535000,0,8,3,...,40,15,490,675,590,750,1000,420,2,0
133,133,Sunbury,380,33.4,10,2128,490000,2,20,20,...,100,100,325,350,320,360,415,360,9,2
134,134,Surrey Hills,630,11.9,4,311,2160000,0,5,20,...,25,100,430,600,468,650,920,500,2,0
135,135,Sydenham,390,21.6,3,407,590000,1,17,20,...,85,100,350,360,350,390,450,400,1,1
136,136,Templestowe,620,16.2,4,359,1415000,0,4,20,...,20,100,440,535,395,480,583,480,2,0
137,137,Thomastown,365,15.6,5,1989,654000,0,11,1,...,55,5,330,373,340,365,420,360,6,0
138,138,Thornbury,550,6.9,6,1295,1211000,0,9,20,...,45,100,400,593,520,600,738,420,6,0
139,139,Toorak,963,5.1,4,660,5050000,1,3,18,...,15,90,495,720,648,1150,1500,500,1,1
140,140,Torquay,520,80.4,2,370,730000,0,6,15,...,30,75,350,445,395,480,550,495,3,0
141,141,Tullamarine,380,16.4,1,933,655000,0,15,20,...,75,100,340,380,340,380,420,380,1,0
142,142,Vermont,450,20.5,4,218,1050000,1,13,13,...,65,65,385,460,400,440,520,450,2,1
143,143,Wantirna,450,23.7,4,482,950000,2,6,20,...,30,100,375,415,388,420,500,440,4,2
144,144,Warragul,360,93.4,8,1222,370000,1,4,8,...,20,40,265,320,280,325,410,325,4,1
145,145,Wendouree,280,104.3,3,1160,265000,1,5,20,...,25,100,240,310,260,310,380,309,4,1
146,146,Werribee,350,28.6,16,3218,478500,4,19,20,...,95,100,305,340,315,350,395,360,8,4
147,147,West Melbourne,600,0.1,1,774,1370000,0,20,20,...,100,100,530,720,540,690,850,450,0,0
148,148,Whittlesea,388,36.0,3,336,469500,0,0,17,...,0,85,300,345,320,365,400,375,2,0
149,149,Williamstown,595,7.5,4,816,1476000,1,0,20,...,0,100,390,653,480,650,820,510,4,1
150,150,Windsor,620,5.3,2,701,1425000,4,8,1,...,40,5,500,650,623,810,1200,435,1,4
151,151,Yarraville,510,6.4,4,701,1000000,0,2,20,...,10,100,383,560,480,550,650,465,4,0

In [2]:
population = pd.read_csv('EthinicityV4 (1).csv')

In [4]:
display(population.head())

,Geometry,Number of Records,Population,REGION,Suburb
0,MULTIPOLYGON,1,71,Metropolitan Region,Abbotsford (Vic.)
1,MULTIPOLYGON,1,0,Metropolitan Region,Aberfeldie
2,MULTIPOLYGON,1,0,Metropolitan Region,Ada
3,MULTIPOLYGON,1,10,Metropolitan Region,Airport West
4,MULTIPOLYGON,1,6,Metropolitan Region,Albanvale

In [5]:
startnew = [{'Suburb':0,'Chinese_population':0}]
temp = pd.DataFrame(startnew)

for i in range(0, len(population)):
    temp.loc[temp.shape[0]] = {'Suburb':population.loc[i]['Suburb'].replace(' (Vic.)',''),'Chinese_population':int(population.loc[i]['Population'])}
    
display(temp)

     Chinese_population              Suburb
0                     0                   0
1                    71          Abbotsford
2                     0          Aberfeldie
3                     0                 Ada
4                    10        Airport West
5                     6           Albanvale
6                     0         Albert Park
7                    13              Albion
8                    38          Alphington
9                    12              Altona
10                   13      Altona Meadows
11                    8        Altona North
12                    0              Ardeer
13                   35            Armadale
14                    0       Arthurs Creek
15                    0        Arthurs Seat
16                   40          Ascot Vale
17                   62           Ashburton
18                   88             Ashwood
19                    5           Aspendale
20                   13   Aspendale Gardens
21                    0             Athlone
22                    0             Attwood
23                   14    Avondale Heights
24                    0          Avonsleigh
25                    0        Badger Creek
26                   11           Balaclava
27                    0            Balliang
28                    0       Balliang East
29                    0          Balnarring
..                  ...                 ...
533                   0         Wattle Glen
534                  22            Werribee
535                   0      Werribee South
536                   0             Wesburn
537                  19      West Footscray
538                 190      West Melbourne
539                   0         Westmeadows
540                 216       Wheelers Hill
541                   0          Whittlesea
542                   0            Wildwood
543                  53    Williams Landing
544                   6        Williamstown
545                   5  Williamstown North
546                  26             Windsor
547                  12             Wollert
548                   5          Wonga Park
549                   0         Woods Point
550                   0           Woodstock
551                   0       Woori Yallock
552                   8        Wyndham Vale
553                   5           Yallambie
554                   0            Yan Yean
555                   0           Yannathan
556                   0          Yarra Glen
557                   0      Yarra Junction
558                   0           Yarrambat
559                  19          Yarraville
560                   0           Yellingbo
561                   0              Yering
562                   0              Yuroke

[563 rows x 2 columns]

In [8]:
finalcheck = pd.merge(temp,result, on='Suburb',how='right')
display(finalcheck)

,Chinese_population,Suburb,Unnamed: 0,Rent,Distance,SchoolNo,CrimeNo,Buy_Price,HospitalNo,SupermarketNo,...,NormSupermarket,NormStation,Rent2bedroomflat,Rent3bedroomflat,Rent2bedroomhouse,Rent3bedroomhouse,Rent4bedroomhouse,RentAverageAll,School_Number,Hospital_Number
0,71.0,Abbotsford,0,630,3.2,3,1154,1290000,0,6,...,30,40,540,800,600,750,0,475,1,0
1,0.0,Albert Park,1,795,3.0,1,605,2150000,0,3,...,15,40,500,790,675,950,1100,570,2,0
2,38.0,Alphington,3,590,7.0,3,219,1778500,1,7,...,35,15,445,590,500,650,800,410,1,1
3,12.0,Altona,4,423,13.2,3,595,950000,1,15,...,75,100,350,410,360,385,420,400,2,1
4,35.0,Armadale,5,835,6.7,2,480,2107500,0,20,...,100,5,500,710,645,900,1330,495,1,0
5,40.0,Ascot Vale,6,510,5.5,3,1046,1192500,1,20,...,100,100,400,525,500,580,730,440,3,0
6,62.0,Ashburton,7,530,11.6,3,354,1815000,1,7,...,35,10,450,550,425,500,630,460,2,1
7,5.0,Aspendale,8,455,26.6,2,253,1122500,1,1,...,5,100,380,475,400,460,550,430,2,1
8,14.0,Avondale Heights,9,420,10.0,2,313,850000,0,1,...,5,100,400,450,400,430,575,420,1,0
9,259.0,Balwyn,10,700,10.4,5,417,2360000,0,8,...,40,100,428,600,430,550,795,520,2,0
10,36.0,Bayswater,12,400,26.9,7,910,805500,1,0,...,0,0,350,400,345,400,445,380,4,1
11,19.0,Beaumaris,13,798,20.1,2,261,1600000,0,5,...,25,100,470,685,525,728,995,570,3,0
12,178.0,Bentleigh,15,580,13.2,4,630,1450000,2,14,...,70,100,443,585,450,550,750,490,2,2
13,101.0,Berwick,16,410,41.2,10,1905,672500,7,10,...,50,50,335,380,340,380,420,400,9,7
14,179.0,Blackburn,17,450,16.8,4,469,1410000,1,19,...,95,20,400,475,390,450,570,430,4,1
15,23.0,Boronia,18,390,29.0,4,1645,731500,1,10,...,50,100,360,410,345,400,465,385,4,1
16,976.0,Box Hill,19,390,13.7,3,1211,1760000,3,9,...,45,100,450,515,400,470,600,435,1,0
17,138.0,Brighton,20,975,11.3,8,930,2830000,4,20,...,100,100,540,750,620,920,1295,650,3,4
18,3.0,Broadmeadows,21,340,15.3,2,2950,545000,1,8,...,40,0,340,360,340,360,430,369,6,1
19,235.0,Brunswick,22,580,5.3,2,2541,1204000,1,18,...,90,0,450,663,530,680,825,460,2,1
20,68.0,Bulleen,23,473,12.5,4,356,1300000,0,2,...,10,100,440,535,395,480,583,480,1,0
21,946.0,Bundoora,24,410,15.8,7,1962,752500,5,9,...,45,65,360,430,360,400,430,390,4,5
22,1068.0,Burwood,26,470,12.3,4,701,1370000,0,16,...,80,100,450,550,425,500,630,460,1,0
23,220.0,Camberwell,27,750,8.4,3,836,2295000,1,8,...,40,100,450,630,533,646,870,490,2,1
24,141.0,Canterbury,28,850,10.5,5,175,3051000,2,18,...,90,10,430,600,468,650,920,500,3,2
25,3169.0,Carlton,29,675,2.0,2,1625,1477500,2,1,...,5,0,520,670,550,775,960,420,2,2
26,685.0,Carnegie,30,490,11.8,1,563,1502500,0,0,...,0,5,440,580,430,550,775,420,1,0
27,9.0,Carrum Downs,31,380,37.4,4,1379,532000,0,4,...,20,100,330,370,330,367,450,370,3,0
28,65.0,Caulfield,33,698,9.3,2,316,1859000,4,18,...,90,100,450,600,520,660,850,453,0,4
29,248.0,Chadstone,34,450,14.1,2,787,1131000,0,2,...,10,20,415,510,410,450,600,450,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122,5.0,Tullamarine,141,380,16.4,1,933,655000,0,15,...,75,100,340,380,340,380,420,380,1,0
123,68.0,Vermont,142,450,20.5,4,218,1050000,1,13,...,65,65,385,460,400,440,520,450,2,1
124,92.0,Wantirna,143,450,23.7,4,482,950000,2,6,...,30,100,375,415,388,420,500,440,4,2
125,22.0,Werribee,146,350,28.6,16,3218,478500,4,19,...,95,100,305,340,315,350,395,360,8,4
126,190.0,West Melbourne,147,600,0.1,1,774,1370000,0,20,...,100,100,530,720,540,690,850,450,0,0
127,0.0,Whittlesea,148,388,36.0,3,336,469500,0,0,...,0,85,300,345,320,365,400,375,2,0
128,6.0,Williamstown,149,595,7.5,4,816,1476000,1,0,...,0,100,390,653,480,650,820,510,4,1
129,26.0,Windsor,150,620,5.3,2,701,1425000,4,8,...,40,5,500,650,623,810,1200,435,1,4
130,19.0,Yarraville,151,510,6.4,4,701,1000000,0,2,...,10,100,383,560,480,550,650,465,4,0
131,NaN,Alfredton,2,360,104.9,2,310,410000,4,2,...,10,95,240,310,260,310,380,309,1,0
132,NaN,Barwon Heads,11,450,66.4,1,120,930500,0,1,...,5,100,340,395,350,400,470,400,1,0
133,NaN,Belmont,14,370,67.7,10,809,495000,1,0,...,0,0,310,378,330,375,430,365,7,1
134,NaN,Buninyong,25,370,96.7,2,134,467500,0,0,...,0,30,245,300,265,325,390,330,1,0
135,NaN,Castlemaine,32,340,106.4,6,427,435000,1,2,...,10,20,285,0,300,348,400,330,4,1
136,NaN,Corio,41,290,60.4,3,1861,305000,0,3,...,15,20,274,318,250,280,340,275,1,0
137,NaN,Delacombe,47,345,104.9,1,411,325000,0,7,...,35,100,240,285,250,280,360,280,1,0
138,NaN,Geelong,65,413,64.6,8,2622,735000,5,14,...,70,80,300,350,320,340,460,330,1,5
139,NaN,Grovedale,71,390,70.7,5,656,432000,1,5,...,25,100,310,378,330,375,430,365,4,1
140,NaN,Herne Hill,76,350,66.8,1,116,490000,0,11,...,55,100,290,395,330,370,473,330,0,0
141,NaN,Kangaroo Flat,81,300,129.9,4,837,310000,1,5,...,25,15,260,310,260,300,350,300,3,0
142,NaN,Lara,86,400,54.0,3,802,430000,0,0,...,0,100,290,345,300,380,440,380,2,0
143,NaN,Moe,94,250,121.2,6,1937,175000,0,0,...,0,100,170,255,200,250,300,210,4,0
144,NaN,Mount Clear,100,330,99.2,3,130,345000,4,1,...,5,100,245,300,265,325,390,330,2,0
145,NaN,Newborough,105,280,123.3,3,535,220000,0,0,...,0,50,170,255,200,250,300,210,3,0
146,NaN,Ocean Grove,112,430,63.5,3,331,630000,0,2,...,10,100,340,395,350,400,470,400,2,0
147,NaN,Sebastopol,126,290,101.7,3,924,257000,0,5,...,25,100,240,285,250,280,360,280,2,0
148,NaN,Seymour,127,300,89.1,1,936,277000,1,5,...,25,20,218,0,260,280,363,270,1,1
149,NaN,Torquay,140,520,80.4,2,370,730000,0,6,...,30,75,350,445,395,480,550,495,3,0
150,NaN,Warragul,144,360,93.4,8,1222,370000,1,4,...,20,40,265,320,280,325,410,325,4,1
151,NaN,Wendouree,145,280,104.3,3,1160,265000,1,5,...,25,100,240,310,260,310,380,309,4,1

In [10]:
finalcheck.to_csv('Results/finaladdpopulation.csv')